server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.corbs: DEBUG
    org.springframework.cloud: DEBUG
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/corbtastik/config-repo
