server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.corbs: DEBUG
    org.springframework.cloud: DEBUG  
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:corbtastik/config-repo.git
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
        encrypt:
          key: |
            -----BEGIN PRIVATE KEY-----
            -----END PRIVATE KEY-----                    
